// Generated by AI
// To Review later

import axios, { AxiosError, InternalAxiosRequestConfig } from "axios";

const api = axios.create({
    baseURL: process.env.NEXT_PUBLIC_API_URL,
    withCredentials: true, 
    headers: {
        "Content-Type": "application/json",
    },
});

// State for managing token refresh
let isRefreshing = false;
let failedQueue: {
    resolve: (value?: unknown) => void;
    reject: (reason?: unknown) => void;
}[] = [];

/**
 * Process all queued requests after token refresh
 * @param error - Error if refresh failed, null if successful
 */
const processQueue = (error: AxiosError | null) => {
    failedQueue.forEach(prom => {
        if (error) {
            prom.reject(error);
        } else {
            prom.resolve();
        }
    });
    failedQueue = [];
};

// Response interceptor to handle token refresh
api.interceptors.response.use(
    response => response,
    async (error: AxiosError) => {
        const originalRequest = error.config as InternalAxiosRequestConfig & {
            _retry?: boolean;
        };

        // If error is not 401 or request already retried, reject immediately
        if (error.response?.status !== 401 || originalRequest._retry) {
            return Promise.reject(error);
        }

        // Skip refresh logic for auth endpoints to avoid infinite loops
        const authEndpoints = ["/auth/login", "/auth/register", "/auth/refresh", "/auth/logout"];
        if (authEndpoints.some(endpoint => originalRequest.url?.includes(endpoint))) {
            return Promise.reject(error);
        }

        // If already refreshing, queue this request
        if (isRefreshing) {
            return new Promise((resolve, reject) => {
                failedQueue.push({ resolve, reject });
            })
                .then(() => api(originalRequest))
                .catch(err => Promise.reject(err));
        }

        originalRequest._retry = true;
        isRefreshing = true;

        try {
            // Attempt to refresh the token
            await api.post("/auth/refresh");

            // Token refreshed successfully, process queued requests
            processQueue(null);

            // Retry the original request
            return api(originalRequest);
        } catch (refreshError) {
            // Refresh failed, process queue with error
            processQueue(refreshError as AxiosError);

            // Optionally redirect to login or handle logout
            if (typeof window !== "undefined") {
                // Clear any client-side state and redirect to login
                window.location.href = "/login";
            }

            return Promise.reject(refreshError);
        } finally {
            isRefreshing = false;
        }
    }
);

// Request interceptor (optional: for logging, adding headers, etc.)
api.interceptors.request.use(
    config => {
        // You can add custom headers here if needed
        // Note: httpOnly cookies are automatically sent by the browser
        return config;
    },
    error => {
        return Promise.reject(error);
    }
);

export default api;
